name: Close stale issues and PRs
on:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-stale: 21
          days-before-close: 0
          exempt-issue-labels: do-not-close
          exempt-pr-labels: do-not-close